version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/codedeploy-source
permissions:
   - object: /home/ec2-user/codedeploy-source
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: installapache.sh
      runas: root
    - location: startapache.sh
      runas: root
   AfterInstall:
    - location: restartapache.sh
      runas: root
