version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/aggregator-codedeploy
permissions:
   - object: /home/ec2-user/aggregator-codedeploy
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
